server {
    listen 80;
    server_name 192.168.205.102;
    return 301 https://$host$request_uri; # Redirige todo a HTTPS automático
}

server {
    listen 443 ssl;
    server_name 192.168.205.102;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    location / {
        proxy_pass http://ohif:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /dcm4chee-arc/ {
        proxy_pass http://dcm4chee:8080/dcm4chee-arc/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /realms/ {
        proxy_pass http://keycloak:8080/realms/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /admin/ {
        proxy_pass http://keycloak:8080/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /resources/ {
        proxy_pass http://keycloak:8080/resources/;
    }
}
